AWSTemplateFormatVersion: '2010-09-09'
Resources:
  APIGateway:
    Properties:
      Cors: '''*'''
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://discjarswaggertemplate/swagger.yaml
      EndpointConfiguration: REGIONAL
      Name: DisciplineJar
      StageName: Prod
    Type: AWS::Serverless::Api
  DisciplineJar:
    Properties:
      PrimaryKey:
        Name: Cookie_Id
        Type: String
      TableName: DisciplineJar
    Type: AWS::Serverless::SimpleTable
  DisciplineJarProposalWriteCookieProposal:
    Properties:
      CodeUri: s3://discjarsambuild/a4189e2b15790a70788b1402523bc682
      Description: A function that writes a new cookie proposal to the proposals table.
      Events:
        DiscJarAPI:
          Properties:
            Auth:
              Authorizer: None
            Method: POST
            Path: /cookieproposal
            RestApiId:
              Ref: APIGateway
          Type: Api
      FunctionName: DisciplineJarProposal_Write_CookieProposal
      Handler: lambda_function.lambda_handler
      MemorySize: 768
      Role:
        Fn::GetAtt:
        - DynamoDBFullControl
        - Arn
      Runtime: python3.7
      Tags:
        Destination: DynamoDB
        Entity: DisciplineJar Proposal
        Operation: Write
        Trigger: API Gateway
      Timeout: 10
    Type: AWS::Serverless::Function
  DisciplineJarProposals:
    Properties:
      PrimaryKey:
        Name: Proposal_Id
        Type: String
      TableName: DisciplineJar_Proposals
    Type: AWS::Serverless::SimpleTable
  DynamoCognitoFullAccess:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      - arn:aws:iam::aws:policy/AmazonCognitoPowerUser
      Path: /
      RoleName: Dynamo_Cognito_FullAccess
    Type: AWS::IAM::Role
  DynamoDBFullControl:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/CloudWatchFullAccess
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Path: /
      RoleName: DynamoDB_FullControl
    Type: AWS::IAM::Role
  SMSServiceSendSMSToUsers:
    Properties:
      CodeUri: s3://discjarsambuild/98780f3997e09f0c43788942a23aa54d
      Description: A function that get's a random cookie, get's all users, loops through
        all users and sends SMS texts to each one.
      Events:
        Cron:
          Properties:
            Description: Every morning at 8am
            Enabled: true
            Name: DailyMorning
            Schedule: cron(0 8 * * ? *)
          Type: Schedule
      FunctionName: SMSService_SendSMSToUsers
      Handler: lambda_function.lambda_handler
      MemorySize: 3008
      Role:
        Fn::GetAtt:
        - DynamoDBFullControl
        - Arn
      Runtime: python3.7
      Tags:
        Destination: nexmo
        Entity: SMSService
        Trigger: Unknown
      Timeout: 30
    Type: AWS::Serverless::Function
  SMSServiceTestingSendToMeOnly:
    Properties:
      CodeUri: s3://discjarsambuild/304c601bd897604ab66fbca15c067f86
      Description: A function that get's a random cookie, get's all users, loops through
        all users and sends SMS texts to each one.
      FunctionName: SMSService_TestingSendToMeOnly
      Handler: lambda_function.lambda_handler
      MemorySize: 3008
      Role:
        Fn::GetAtt:
        - DynamoDBFullControl
        - Arn
      Runtime: python3.7
      Tags:
        Destination: nexmo
        Entity: SMSService
        Trigger: Unknown
      Timeout: 30
    Type: AWS::Serverless::Function
  User:
    Properties:
      PrimaryKey:
        Name: Phone_Num
        Type: String
      TableName: User
    Type: AWS::Serverless::SimpleTable
  UserReadDoesUserExist:
    Properties:
      CodeUri: s3://discjarsambuild/1c8f659134cf3b7a435d99a5a0c176d5
      Description: A function that returns whether or not a user exists already.
      Events:
        DiscJarAPI:
          Properties:
            Auth:
              Authorizer: None
            Method: GET
            Path: /user/exists
            RestApiId:
              Ref: APIGateway
          Type: Api
      FunctionName: User_Read_DoesUserExist
      Handler: lambda_function.lambda_handler
      MemorySize: 768
      Role:
        Fn::GetAtt:
        - DynamoDBFullControl
        - Arn
      Runtime: python3.7
      Tags:
        Destination: DynamoDB
        Entity: User
        Operation: Read
        Trigger: API Gateway
      Timeout: 10
    Type: AWS::Serverless::Function
  UserReadSettings:
    Properties:
      CodeUri: s3://discjarsambuild/39a40cc4dc6256cb7b36a161aec76239
      Description: A function that writes User Settings to DynamoDB
      Events:
        DiscJarAPI:
          Properties:
            Auth:
              Authorizer: None
            Method: GET
            Path: /user/settings
            RestApiId:
              Ref: APIGateway
          Type: Api
      FunctionName: User_Read_Settings
      Handler: lambda_function.lambda_handler
      MemorySize: 768
      Role:
        Fn::GetAtt:
        - DynamoDBFullControl
        - Arn
      Runtime: python3.7
      Tags:
        Destination: DynamoDB
        Entity: User
        Operation: Read
        Trigger: API Gateway
      Timeout: 10
    Type: AWS::Serverless::Function
  UserWriteSettings:
    Properties:
      CodeUri: s3://discjarsambuild/d3f472bcc2048eaeb0052166c6dd7c6a
      Description: A function that writes User Settings to DynamoDB
      Events:
        DiscJarAPI:
          Properties:
            Auth:
              Authorizer: None
            Method: POST
            Path: /user/settings
            RestApiId:
              Ref: APIGateway
          Type: Api
      FunctionName: User_Write_Settings
      Handler: lambda_function.lambda_handler
      MemorySize: 768
      Role:
        Fn::GetAtt:
        - DynamoDBFullControl
        - Arn
      Runtime: python3.7
      Tags:
        Destination: DynamoDB
        Entity: User
        Operation: Write
        Trigger: API Gateway
      Timeout: 10
    Type: AWS::Serverless::Function
  UserWriteSignup:
    Properties:
      CodeUri: s3://discjarsambuild/91d559bbdeb1adb09f48a13cec642903
      Description: A function that is triggered by API gateway and writes a user to
        the user table.
      Events:
        DiscJarAPI:
          Properties:
            Auth:
              Authorizer: None
            Method: POST
            Path: /user/signup
            RestApiId:
              Ref: APIGateway
          Type: Api
      FunctionName: User_Write_Signup
      Handler: lambda_function.lambda_handler
      MemorySize: 768
      Role:
        Fn::GetAtt:
        - DynamoDBFullControl
        - Arn
      Runtime: python3.7
      Tags:
        Destination: DynamoDB
        Entity: User
        Operation: Write
        Trigger: API Gateway
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
