AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  #API Gateway
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: DisciplineJar
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Cors: "'*'"
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: s3://discjarswaggertemplate/swagger.yaml

  #====================================================================================================================

  #Lambda Functions

  #User Entity

  UserWriteSignup:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: User_Write_Signup
      Description: A function that is triggered by API gateway and writes a user to the user table.
      CodeUri: User_Write_Signup/
      Handler: lambda_function.lambda_handler
      Role: !GetAtt DynamoDBFullControl.Arn
      Runtime: python3.7
      Timeout: 10
      MemorySize: 768
      Events:
        DiscJarAPI:
          Type: Api
          Properties:
            RestApiId: 
              Ref: APIGateway
            Path: /user/signup
            Method: POST
            Auth:
              Authorizer: None
      Tags:
        Entity: User
        Trigger: API Gateway
        Operation: Write
        Destination: DynamoDB
      
  UserWriteSettings:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: User_Write_Settings
      Description: A function that writes User Settings to DynamoDB
      CodeUri: User_Write_Settings/
      Handler: lambda_function.lambda_handler
      Role: !GetAtt DynamoDBFullControl.Arn
      Runtime: python3.7
      Timeout: 10
      MemorySize: 768
      Events:
        DiscJarAPI:
          Type: Api
          Properties:
            RestApiId: 
              Ref: APIGateway
            Path: /user/settings
            Method: POST
            Auth:
              Authorizer: None
      Tags:
        Entity: User
        Trigger: API Gateway
        Operation: Write
        Destination: DynamoDB

  UserReadSettings:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: User_Read_Settings
      Description: A function that writes User Settings to DynamoDB
      CodeUri: User_Read_Settings/
      Handler: lambda_function.lambda_handler
      Role: !GetAtt DynamoDBFullControl.Arn
      Runtime: python3.7
      Timeout: 10
      MemorySize: 768
      Events:
        DiscJarAPI:
          Type: Api
          Properties:
            RestApiId: 
              Ref: APIGateway
            Path: /user/settings
            Method: GET
            Auth:
              Authorizer: None
      Tags:
        Entity: User
        Trigger: API Gateway
        Operation: Read
        Destination: DynamoDB

  UserReadDoesUserExist:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: User_Read_DoesUserExist
      Description: A function that returns whether or not a user exists already.
      CodeUri: User_Read_DoesUserExist/
      Handler: lambda_function.lambda_handler
      Role: !GetAtt DynamoDBFullControl.Arn
      Runtime: python3.7
      Timeout: 10
      MemorySize: 768
      Events:
        DiscJarAPI:
          Type: Api
          Properties:
            RestApiId: 
              Ref: APIGateway
            Path: /user/exists
            Method: GET
            Auth:
              Authorizer: None
      Tags:
        Entity: User
        Trigger: API Gateway
        Operation: Read
        Destination: DynamoDB

#End of User Lambdas
#-------------------------------------------------------------------------------

#End of Lambdas
#==========================================================================================================

#Start of IAM Roles
  DynamoCognitoFullAccess:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Dynamo_Cognito_FullAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: 
              - "lambda.amazonaws.com"
          Action: 
            - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
        - "arn:aws:iam::aws:policy/AmazonCognitoPowerUser"
      Path: "/"
  
  DynamoDBFullControl:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DynamoDB_FullControl
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: 
              - "lambda.amazonaws.com"
          Action: 
            - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/CloudWatchFullAccess"
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
      Path: "/"

#End of IAM
#==========================================================================================================

#Start of DynamoDB Tables
  User:
    Properties:
      PrimaryKey:
        Name: Phone_Num
        Type: String
      TableName: User
    Type: AWS::Serverless::SimpleTable
    
  Content:
    Properties:
      PrimaryKey:
        Name: Content_Id
        Type: String
      TableName: Content
    Type: AWS::Serverless::SimpleTable

#End of DynamoDB Tables
#=================================================================================================
